const db= require('../config/database');
const winston = require('winston');

const logger = winston.createLogger({
  level: process.env.LOG_LEVEL || 'info',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  transports: [
    new winston.transports.File({ filename: 'logs/database.log' }),
    new winston.transports.Console({ format: winston.format.simple() })
  ]
});

class DatabaseService {
  async getCameras() {
    return db('camera').select('*').where({ connectivityStatus: 'active' });
  }
  async getAIModels() {
    return db('aiModels').select('*');
  }
  async insertVehicleLog(logData) {
  // Transform data to match your table structure exactly
  const dbLogData = {
    time: logData.eventTime || logData.time, // Handle both formats
    eventType: logData.eventType,
    screenShotPath: logData.screenshotPath || logData.screenShotPath, // Handle both formats
    cameraId: logData.cameraId,
    location: logData.location,
    office_id: logData.office_id || null,
    // created_at and updated_at should be auto-generated by database
  };
  
  console.log('Inserting log data:', dbLogData); // Debug log
  
  const [insertedLog] = await db('vehicleInOutModelLogs').insert(dbLogData).returning('*');
  return insertedLog;
}
  async getVehicleLogs(filters = {}) {
    let query = db('vehicleInOutModelLogs').select('*');
    if (filters.cameraId) query = query.where('cameraId', filters.cameraId);
    if (filters.startDate) query = query.where('createdAt', '>=', filters.startDate);
    if (filters.endDate) query = query.where('createdAt', '<=', filters.endDate);
    if (filters.limit) query = query.limit(filters.limit);
    return query.orderBy('created_at', 'desc');
  }
}

module.exports = new DatabaseService();